import React,{useEffect,useRef}from'react';import{Animated,StyleSheet,Text,TouchableOpacity,View,TextInput,ScrollView}from'react-native';import{Ionicons,MaterialCommunityIcons}from'@expo/vector-icons';
export const C={bg:'#050507',card:'rgba(255,255,255,.08)',line:'rgba(255,255,255,.24)',text:'#fff',muted:'rgba(255,255,255,.72)',danger:'#ff6b6b',ok:'#8affc1',warn:'#ffd166'};
export function StarBackground({children}){const a=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.loop(Animated.sequence([Animated.timing(a,{toValue:1,duration:2600,useNativeDriver:true}),Animated.timing(a,{toValue:0,duration:2600,useNativeDriver:true})])).start()},[]);const stars=Array.from({length:42},(_,i)=><Animated.View key={i} style={[s.star,{left:`${(i*37)%100}%`,top:`${(i*61)%100}%`,opacity:a.interpolate({inputRange:[0,1],outputRange:[.25,1]}),transform:[{scale:a.interpolate({inputRange:[0,1],outputRange:[.55+(i%4)/10,1.1]})}]}]}/>);return <View style={s.bg}>{stars}{children}</View>}
export function Header({title,onBack,icon='flash-outline'}){return <View style={s.header}>{onBack&&<TouchableOpacity onPress={onBack} style={s.iconBtn}><Ionicons name="home-outline" size={22} color="#fff"/></TouchableOpacity>}<MaterialCommunityIcons name={icon} size={26} color="#fff"/><Text style={s.title}>{title}</Text></View>}
export function Button({title,onPress,icon='sparkles-outline',disabled,type}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.btn,disabled&&{opacity:.45},type==='danger'&&{borderColor:C.danger}]}><Ionicons name={icon} size={18} color="#fff"/><Text style={s.btnText}>{title}</Text></TouchableOpacity>}
export function Input(p){return <TextInput placeholderTextColor="rgba(255,255,255,.48)" textAlign="right" style={[s.input,p.multiline&&s.area,p.style]} {...p}/>}
export function Card({children,style}){return <View style={[s.card,style]}>{children}</View>}
export function Segments({items,value,onChange}){return <View style={s.segs}>{items.map(it=><TouchableOpacity key={it} onPress={()=>onChange(it)} style={[s.seg,value===it&&s.segActive]}><Text style={s.segText}>{it}</Text></TouchableOpacity>)}</View>}
export function Page({children}){return <StarBackground><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>{children}</ScrollView></StarBackground>}
export const s=StyleSheet.create({bg:{flex:1,backgroundColor:C.bg},star:{position:'absolute',width:2,height:2,borderRadius:4,backgroundColor:'#fff'},page:{padding:16,paddingBottom:44},header:{paddingTop:24,paddingBottom:18,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:10},title:{color:C.text,fontSize:24,fontWeight:'900',textAlign:'center'},iconBtn:{position:'absolute',left:0,top:20,borderWidth:1,borderColor:C.line,borderRadius:14,padding:10,backgroundColor:C.card},card:{borderWidth:1,borderColor:C.line,backgroundColor:C.card,borderRadius:22,padding:14,marginBottom:14},btn:{borderWidth:1,borderColor:C.line,backgroundColor:'rgba(255,255,255,.12)',borderRadius:16,padding:13,marginVertical:5,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:8},btnText:{color:C.text,fontSize:15,fontWeight:'800',textAlign:'center'},input:{borderWidth:1,borderColor:C.line,backgroundColor:'rgba(0,0,0,.32)',color:C.text,borderRadius:16,padding:12,marginVertical:7,fontSize:15},area:{minHeight:130,textAlignVertical:'top'},label:{color:C.text,fontWeight:'800',fontSize:15,marginTop:6,textAlign:'right'},muted:{color:C.muted,textAlign:'right',lineHeight:22},segs:{flexDirection:'row-reverse',borderWidth:1,borderColor:C.line,borderRadius:16,overflow:'hidden',marginVertical:8},seg:{flex:1,padding:11,alignItems:'center',backgroundColor:'rgba(255,255,255,.05)'},segActive:{backgroundColor:'rgba(255,255,255,.22)'},segText:{color:C.text,fontWeight:'800'},row:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'}});
